version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: thenews-db
    environment:
      POSTGRES_DB: thenews
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432" # Map host port 5432 to container port 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
